language: node_js
node_js: "stable"
install:
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - createuser mrKingz -s -U postgres
  - createdb events_manager_db_test --username=mrKingz
  - sequelize db:migrate
  - sequelize db:seed:all
after_success:
  - npm run coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info